name: ImageCompress
options:
  bundleIdPrefix: com.imagecompress
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: zh-Hans
  
targets:
  ImageCompress:
    type: application
    platform: macOS
    sources:
      - path: .
        excludes:
          - "*.md"
          - "*.sh"
          - "project.yml"
    settings:
      base:
        PRODUCT_NAME: ImageCompress
        PRODUCT_BUNDLE_IDENTIFIER: com.imagecompress.app
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
    dependencies: []
