#!/bin/bash

# 创建 Xcode 项目的脚本
# 由于无法直接生成 .xcodeproj 文件,我们提供手动创建步骤

echo "==================================="
echo "ImageCompress Xcode 项目创建指南"
echo "==================================="
echo ""
echo "请按照以下步骤在 Xcode 中创建项目:"
echo ""
echo "1. 打开 Xcode"
echo "2. 选择 'File > New > Project'"
echo "3. 选择 'macOS > App'"
echo "4. 填写项目信息:"
echo "   - Product Name: ImageCompress"
echo "   - Team: (选择你的开发团队)"
echo "   - Organization Identifier: com.yourname"
echo "   - Interface: SwiftUI"
echo "   - Language: Swift"
echo "5. 保存位置选择当前目录的父目录"
echo "6. 删除 Xcode 自动生成的文件"
echo "7. 将现有的源文件添加到项目中:"
echo "   - 右键点击项目 > Add Files to 'ImageCompress'"
echo "   - 选择以下文件夹:"
echo "     * ImageCompressApp.swift"
echo "     * Models/"
echo "     * Views/"
echo "     * Engine/"
echo "     * Utils/"
echo "     * Assets.xcassets"
echo "     * Info.plist"
echo ""
echo "或者,使用以下快速方法:"
echo ""
echo "运行以下命令安装 xcodegen (如果尚未安装):"
echo "  brew install xcodegen"
echo ""
echo "然后在项目目录运行:"
echo "  xcodegen generate"
echo ""
echo "==================================="
echo ""
echo "项目文件已准备就绪,位于:"
echo "$(pwd)"
echo ""
echo "所有源文件:"
find . -name "*.swift" -o -name "*.plist" -o -name "*.json" | grep -v ".build"
